// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkStationX.Data;

#nullable disable

namespace WorkStationX.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WorkStationX.Models.ChromeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileDirectory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileDirectory")
                        .IsUnique();

                    b.ToTable("ChromeProfiles");
                });

            modelBuilder.Entity("WorkStationX.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFiredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextFireUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SnoozeUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeOfDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("WorkStationX.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualSecondsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemainingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WorkStationX.Models.TaskSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasExtension")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskSessions");
                });

            modelBuilder.Entity("WorkStationX.Models.TimeBankEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeltaSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TimeBankEntries");
                });

            modelBuilder.Entity("WorkStationX.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLaunchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("WorkStationX.Models.WorkspaceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChromeProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchArguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChromeProfileId");

                    b.ToTable("WorkspaceItems");
                });

            modelBuilder.Entity("WorkStationX.Models.WorkspaceItemLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaunchOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkspaceItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceItemId");

                    b.HasIndex("WorkspaceId", "WorkspaceItemId")
                        .IsUnique();

                    b.ToTable("WorkspaceItemLinks");
                });

            modelBuilder.Entity("WorkStationX.Models.TaskSession", b =>
                {
                    b.HasOne("WorkStationX.Models.TaskItem", "TaskItem")
                        .WithMany("Sessions")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("WorkStationX.Models.TimeBankEntry", b =>
                {
                    b.HasOne("WorkStationX.Models.TaskItem", "TaskItem")
                        .WithMany("TimeBankEntries")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("WorkStationX.Models.WorkspaceItem", b =>
                {
                    b.HasOne("WorkStationX.Models.ChromeProfile", "ChromeProfile")
                        .WithMany()
                        .HasForeignKey("ChromeProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChromeProfile");
                });

            modelBuilder.Entity("WorkStationX.Models.WorkspaceItemLink", b =>
                {
                    b.HasOne("WorkStationX.Models.Workspace", "Workspace")
                        .WithMany("ItemLinks")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkStationX.Models.WorkspaceItem", "WorkspaceItem")
                        .WithMany("WorkspaceLinks")
                        .HasForeignKey("WorkspaceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");

                    b.Navigation("WorkspaceItem");
                });

            modelBuilder.Entity("WorkStationX.Models.TaskItem", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("TimeBankEntries");
                });

            modelBuilder.Entity("WorkStationX.Models.Workspace", b =>
                {
                    b.Navigation("ItemLinks");
                });

            modelBuilder.Entity("WorkStationX.Models.WorkspaceItem", b =>
                {
                    b.Navigation("WorkspaceLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
